name: 'Egress Filter'
description: 'Transparent proxy with eBPF-based PID tracking for monitoring network egress'
author: 'gregclermont'

inputs:
  policy:
    description: 'Egress policy rules (one rule per line)'
    required: false
    default: ''
  audit:
    description: 'Run in audit mode (log only, do not block)'
    required: false
    default: 'false'
  allow-sudo:
    description: 'Allow sudo for the runner user (less secure, needed for some actions like Tailscale)'
    required: false
    default: 'false'
  upload-log:
    description: 'Upload connection log as workflow artifact (default: only when audit mode, blocks, or errors)'
    required: false

runs:
  using: 'node24'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

branding:
  icon: 'shield'
  color: 'blue'
